name: Bug report
description: File a bug
body:
  - type: checkboxes
    attributes:
      label: Checkboxes
      options:
        - label: I have read the [installation](https://xxyzz.github.io/WordDumb/installation.html) and [usage](https://xxyzz.github.io/WordDumb/usage.html) documents.
          required: true
        - label: I have not found similar open/closed issue or disscussion.
          required: true
        - label: Reboot doesn't fix the problem.
          required: true

  - type: textarea
    attributes:
      label: Describe the bug and copy the error message
    validations:
      required: true

  - type: textarea
    attributes:
      label: Plugin settings and reproduce steps
      placeholder: |
        0. Enable the X feature
        1. Go to ...
        2. Click on ...
        3. Scroll down to ...
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Generated files, screenshots or videos
      description: Drag files here if they are helpful for solving the issue.
